services:
  - type: web
    name: fraud-detection-api
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip && pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /
    # Force rebuild
    buildFilter:
      paths:
        - api/requirements.txt
        - render.yaml